#!/bin/bash
# Quick Start Guide for State Design Pattern

echo "🚀 State Design Pattern - Quick Start"
echo "======================================"
echo ""
echo "1. Install dependencies:"
echo "   npm install"
echo ""
echo "2. Build the TypeScript files:"
echo "   npm run build"
echo ""
echo "3. Run the examples:"
echo "   npm start"
echo ""
echo "4. Development mode (auto-compile):"
echo "   npm run dev"
echo ""
echo "5. Clean build artifacts:"
echo "   npm run clean"
echo ""
echo "======================================"
echo "📁 Project Structure:"
echo "======================================"
echo "exam/"
echo "├── src/"
echo "│   ├── behavioral/"
echo "│   │   └── State/"
echo "│   │       ├── State.ts              (Interface & Abstract class)"
echo "│   │       ├── ConcreteStates.ts     (RedState, YellowState, GreenState)"
echo "│   │       ├── Context.ts            (TrafficLight, Document classes)"
echo "│   │       └── index.ts              (Exports)"
echo "│   └── examples/"
echo "│       └── example.ts                (Usage demonstrations)"
echo "├── .editorconfig"
echo "├── .gitignore"
echo "├── package.json"
echo "├── tsconfig.json"
echo "├── STATE_PATTERN.md"
echo "└── README.md"
echo ""
echo "======================================"
echo "📚 Key Files:"
echo "======================================"
echo "1. State.ts - Defines the State interface and abstract base class"
echo "2. ConcreteStates.ts - Implements specific states (Red, Yellow, Green)"
echo "3. Context.ts - Manages state switching (TrafficLight, Document)"
echo "4. example.ts - Demonstrates usage with two examples"
echo "5. STATE_PATTERN.md - Comprehensive documentation"
echo ""
echo "======================================"
echo "✨ Examples:"
echo "======================================"
echo "1. Traffic Light State Machine"
echo "   - RedState → YellowState → GreenState → RedState"
echo ""
echo "2. Document Workflow"
echo "   - DraftState → ReviewState → PublishedState → ArchivedState"
echo ""
echo "======================================"
